# Generated by Django 2.2 on 2019-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=10)),
                ('project_id', models.CharField(max_length=10)),
                ('rev_value', models.TextField()),
                ('ip', models.CharField(max_length=15)),
                ('method', models.CharField(max_length=6)),
                ('referer', models.CharField(max_length=50)),
                ('ua', models.CharField(max_length=200)),
                ('status', models.CharField(default='True', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('filename', models.CharField(max_length=100)),
                ('explain', models.CharField(max_length=200)),
                ('parameter', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=10)),
                ('describe', models.CharField(max_length=500)),
                ('create_time', models.CharField(max_length=50)),
                ('payload', models.CharField(max_length=30)),
                ('send_email', models.CharField(max_length=5)),
                ('short_url', models.CharField(max_length=30)),
                ('keep_alive', models.CharField(max_length=5)),
                ('diy_payload', models.CharField(max_length=10000)),
                ('payload_parameter', models.CharField(max_length=200)),
            ],
        ),
    ]
