# Generated by Django 2.2 on 2019-05-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='parameter',
            field=models.CharField(max_length=100),
        ),
    ]
